name: ${project.name}
version: ${project.version}
api-version: 1.13
main: ${project.groupId}.${project.artifactId}.${project.name}
authors: [GabrielHD55, MikeLara]
depend:
  - Citizens
softdepend:
  - MultiWorld
  - Multiverse-Core
  - PlaceholderAPI
commands:
  pirates:
    usage: /<command>
    aliases:
      - pirate
  stats:
    usage: /<command>
  join:
    usage: /<command>
  leave:
    usage: /<command>
  games:
    usage: /<command>